name: multi_builder
description: "Easily use multiple TransitionBuilder in WidgetsApp MaterialApp or CupertinoApp."
version: 1.4.0
repository: https://github.com/wyq0918dev/multi_builder

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
